/**
 * AR Invoice line row shape as returned from the API / database (INV1).
 * Field names match source columns, including legacy spellings/casing.
 * Nullability and primitive types are inferred from the provided sample row.
 */
export type ArInvoiceLine = {
  DocEntry: number;
  LineNum: number;
  TargetType: number;
  TrgetEntry: number | null;
  BaseRef: string;
  BaseType: number;
  BaseEntry: number;
  BaseLine: number;
  LineStatus: string;
  ItemCode: string;
  Dscription: string;
  Quantity: number;
  ShipDate: string;
  OpenQty: number;
  Price: number;
  Currency: string;
  Rate: number;
  DiscPrcnt: number;
  LineTotal: number;
  TotalFrgn: number;
  OpenSum: number;
  OpenSumFC: number;
  VendorNum: string | null;
  SerialNum: string | null;
  WhsCode: string;
  SlpCode: number;
  Commission: number;
  TreeType: string;
  AcctCode: string;
  TaxStatus: string;
  GrossBuyPr: number;
  PriceBefDi: number;
  DocDate: string;
  Flags: number;
  OpenCreQty: number;
  UseBaseUn: string;
  SubCatNum: string | null;
  BaseCard: string;
  TotalSumSy: number;
  OpenSumSys: number;
  InvntSttus: string;
  OcrCode: string | null;
  Project: string;
  CodeBars: string | null;
  VatPrcnt: number;
  VatGroup: string;
  PriceAfVAT: number;
  Height1: number;
  Hght1Unit: string | null;
  Height2: number;
  Hght2Unit: string | null;
  Width1: number;
  Wdth1Unit: string | null;
  Width2: number;
  Wdth2Unit: string | null;
  Length1: number;
  Len1Unit: string | null;
  length2: number;
  Len2Unit: string | null;
  Volume: number;
  VolUnit: number;
  Weight1: number;
  Wght1Unit: string | null;
  Weight2: number;
  Wght2Unit: string | null;
  Factor1: number;
  Factor2: number;
  Factor3: number;
  Factor4: number;
  PackQty: number;
  UpdInvntry: string;
  BaseDocNum: number;
  BaseAtCard: string;
  SWW: string | null;
  VatSum: number;
  VatSumFrgn: number;
  VatSumSy: number;
  FinncPriod: number;
  ObjType: string;
  LogInstanc: number;
  BlockNum: string | null;
  ImportLog: string | null;
  DedVatSum: number;
  DedVatSumF: number;
  DedVatSumS: number;
  IsAqcuistn: string;
  DistribSum: number;
  DstrbSumFC: number;
  DstrbSumSC: number;
  GrssProfit: number;
  GrssProfSC: number;
  GrssProfFC: number;
  VisOrder: number;
  INMPrice: number;
  PoTrgNum: string | null;
  PoTrgEntry: string | null;
  DropShip: string;
  PoLineNum: string | null;
  Address: string;
  TaxCode: string | null;
  TaxType: string;
  OrigItem: string | null;
  BackOrdr: string;
  FreeTxt: string;
  PickStatus: string;
  PickOty: number;
  PickIdNo: string | null;
  TrnsCode: number;
  VatAppld: number;
  VatAppldFC: number;
  VatAppldSC: number;
  BaseQty: number;
  BaseOpnQty: number;
  VatDscntPr: number;
  WtLiable: string;
  DeferrTax: string;
  EquVatPer: number;
  EquVatSum: number;
  EquVatSumF: number;
  EquVatSumS: number;
  LineVat: number;
  LineVatlF: number;
  LineVatS: number;
  unitMsr: string | null;
  NumPerMsr: number;
  CEECFlag: string;
  ToStock: number;
  ToDiff: number;
  ExciseAmt: number;
  TaxPerUnit: number;
  TotInclTax: number;
  CountryOrg: string | null;
  StckDstSum: number;
  ReleasQtty: number;
  LineType: string;
  TranType: string | null;
  Text: string | null;
  OwnerCode: string | null;
  StockPrice: number;
  ConsumeFCT: string;
  LstByDsSum: number;
  StckINMPr: number;
  LstBINMPr: number;
  StckDstFc: number;
  StckDstSc: number;
  LstByDsFc: number;
  LstByDsSc: number;
  StockSum: number;
  StockSumFc: number;
  StockSumSc: number;
  StckSumApp: number;
  StckAppFc: number;
  StckAppSc: number;
  ShipToCode: string;
  ShipToDesc: string;
  StckAppD: number;
  StckAppDFC: number;
  StckAppDSC: number;
  BasePrice: string;
  GTotal: number;
  GTotalFC: number;
  GTotalSC: number;
  DistribExp: string;
  DescOW: string;
  DetailsOW: string;
  GrossBase: number;
  VatWoDpm: number;
  VatWoDpmFc: number;
  VatWoDpmSc: number;
  CFOPCode: string | null;
  CSTCode: string | null;
  Usage: string | null;
  TaxOnly: string;
  WtCalced: string;
  QtyToShip: number;
  DelivrdQty: number;
  OrderedQty: number;
  CogsOcrCod: string | null;
  CiOppLineN: number;
  CogsAcct: string;
  ChgAsmBoMW: string;
  ActDelDate: string;
  OcrCode2: string | null;
  OcrCode3: string | null;
  OcrCode4: string | null;
  OcrCode5: string | null;
  TaxDistSum: number;
  TaxDistSFC: number;
  TaxDistSSC: number;
  PostTax: string;
  Excisable: string | null;
  AssblValue: number;
  RG23APart1: string | null;
  RG23APart2: string | null;
  RG23CPart1: string | null;
  RG23CPart2: string | null;
  CogsOcrCo2: string | null;
  CogsOcrCo3: string | null;
  CogsOcrCo4: string | null;
  CogsOcrCo5: string | null;
  LnExcised: string | null;
  LocCode: string | null;
  StockValue: number;
  GPTtlBasPr: number;
  unitMsr2: string | null;
  NumPerMsr2: number;
  SpecPrice: string;
  CSTfIPI: string | null;
  CSTfPIS: string | null;
  CSTfCOFINS: string | null;
  ExLineNo: string | null;
  isSrvCall: string;
  PQTReqQty: number;
  PQTReqDate: string | null;
  PcDocType: number;
  PcQuantity: number;
  LinManClsd: string;
  VatGrpSrc: string;
  NoInvtryMv: string;
  ActBaseEnt: string | null;
  ActBaseLn: string | null;
  ActBaseNum: string | null;
  OpenRtnQty: number;
  AgrNo: string | null;
  AgrLnNum: string | null;
  CredOrigin: string | null;
  Surpluses: number;
  DefBreak: number;
  Shortages: number;
  UomEntry: number;
  UomEntry2: number;
  UomCode: string;
  UomCode2: string;
  FromWhsCod: string | null;
  NeedQty: string;
  PartRetire: string;
  RetireQty: number;
  RetireAPC: number;
  RetirAPCFC: number;
  RetirAPCSC: number;
  InvQty: number;
  OpenInvQty: number;
  EnSetCost: string;
  RetCost: number;
  Incoterms: number;
  TransMod: number;
  LineVendor: string | null;
  DistribIS: string;
  ISDistrb: number;
  ISDistrbFC: number;
  ISDistrbSC: number;
  IsByPrdct: string;
  ItemType: number;
  PriceEdit: string;
  PrntLnNum: string | null;
  LinePoPrss: string;
  FreeChrgBP: string;
  TaxRelev: string;
  LegalText: string | null;
  ThirdParty: string;
  LicTradNum: string | null;
  InvQtyOnly: string;
  UnencReasn: string | null;
  ShipFromCo: string | null;
  ShipFromDe: string | null;
  FisrtBin: string | null;
  AllocBinC: string | null;
  ExpType: string | null;
  ExpUUID: string | null;
  ExpOpType: string | null;
  DIOTNat: string | null;
  MYFtype: string | null;
  GPBefDisc: number;
  ReturnRsn: number;
  ReturnAct: number;
  StgSeqNum: string | null;
  StgEntry: string | null;
  StgDesc: string | null;
  ItmTaxType: string | null;
  SacEntry: string | null;
  NCMCode: number;
  HsnEntry: string | null;
  OriBAbsEnt: string | null;
  OriBLinNum: string | null;
  OriBDocTyp: string | null;
  IsPrscGood: string;
  IsCstmAct: string;
  EncryptIV: string | null;
  ExtTaxRate: number;
  ExtTaxSum: number;
  TaxAmtSrc: string;
  ExtTaxSumF: number;
  ExtTaxSumS: number;
  StdItemId: string | null;
  CommClass: string | null;
  VatExEntry: string | null;
  VatExLN: string | null;
  NatOfTrans: string | null;
  ISDtCryImp: string | null;
  ISDtRgnImp: string | null;
  ISOrCryExp: string | null;
  ISOrRgnExp: string | null;
  NVECode: string | null;
  PoNum: string | null;
  PoItmNum: string | null;
  IndEscala: string;
  CESTCode: string | null;
  CtrSealQty: number;
  CNJPMan: string | null;
  UFFiscBene: string | null;
  CUSplit: string;
  LegalTIMD: string | null;
  LegalTTCA: string | null;
  LegalTW: string | null;
  LegalTCD: string | null;
  RevCharge: string;
  U_BLNo: string | null;
  U_NoOfContainers: string | null;
  U_ConsigneeName: string | null;
  U_ConsigneeAdd: string | null;
  U_NotifyName: string | null;
  U_NotifyAdd: string | null;
  U_FreightInd: string | null;
  U_TransitLocal: string | null;
  U_GRItemDetails: string | null;
  U_GRDestination: string | null;
  U_GRDelivery: string | null;
  U_GRVesselName: string | null;
  U_GRVoyage: string | null;
  U_GRContainerSize: string | null;
  U_DName: string | null;
  U_DLicNum: string | null;
  U_TruckNo: string | null;
  U_CustCode: string | null;
  U_Email: string | null;
  U_CGL: string | null;
  U_CGLN: string | null;
  U_DGL: string | null;
  U_DGLN: string | null;
  U_APInvNo: string | null;
  U_Weive: string;
  U_WaiveAmt: number;
  U_Factor1: number;
  U_Factor2: number;
  U_ChasisNo: string | null;
  U_NOP: number;
  U_FTP: string | null;
};
