/**
 * ContainerData  header row shape as returned from the API / database.
 * Field names match the source columns, including legacy spellings.
 */
export type ContainerDataHeader = {
  DocEntry: number;
  DocNum: number;
  Period: number;
  Instance: number;
  Series: number;
  Handwrtten: string;
  Canceled: string;
  Object: string;
  LogInst: number | null;
  UserSign: number;
  Transfered: string;
  Status: string;
  CreateDate: string;
  CreateTime: number;
  UpdateDate: string;
  UpdateTime: number;
  DataSource: string;
  RequestStatus: string;
  Creator: string;
  Remark: string | null;
  U_MBLNo: string | null;
  U_HBLNo: string | null;
  U_MRN: string | null;
  U_VN: string | null;
  U_CHA: string | null;
  U_CHAAN: string | null;
  U_Labour: string | null;
  U_TANSAD: string | null;
  U_OrderD: string | null;
  U_OrderT: number | null;
  U_CustCode: string | null;
  U_CustName: string | null;
  U_Status: string | null;
  U_CRN: string | null;
  U_CRD: string | null;
  U_DON: string | null;
  U_DOD: string | null;
  U_DED: string | null;
  U_DisDate: string | null;
  U_CustV: number;
  U_CustD: number;
  U_Status1: string | null;
  U_IMDG: string | null;
  U_DOG: string | null;
  U_CRDate: string | null;
  U_AgrId: string | null;
  U_ValidDate: string | null;
  U_FreeDV: string | null;
  U_FI: string | null;
  U_POD: string | null;
  U_CT: string | null;
  U_COI: string | null;
  U_DC: string | null;
  U_PortVerification: string | null;
  U_PortStripping: string | null;
  U_MSPC: number;
  U_MAgrId: string | null;
  U_MValidDate: string | null;
  U_CP: string | null;
  U_Per: number;
  U_DTime: number | null;
  U_CRTime: number | null;
  U_FBPD: string | null;
  U_InvF: string | null;
  U_MIBQTY: string | null;
};
