/**
 * Gate Out document header (OIGE / goods issue style) as returned from the API / database.
 * Field names match the source columns, including legacy spellings (CANCELED, Handwrtten, etc.).
 * Nullable fields follow the sample; selected SAP integer columns use number | null when null.
 */
export type GateOutDataHeader = {
  DocEntry: number;
  DocNum: number;
  DocType: string;
  CANCELED: string;
  Handwrtten: string;
  Printed: string;
  DocStatus: string;
  InvntSttus: string;
  Transfered: string;
  ObjType: string;
  DocDate: string;
  DocDueDate: string;
  CardCode: string | null;
  CardName: string | null;
  Address: string;
  NumAtCard: string | null;
  VatPercent: number;
  VatSum: number;
  VatSumFC: number;
  DiscPrcnt: number;
  DiscSum: number;
  DiscSumFC: number;
  DocCur: string;
  DocRate: number;
  DocTotal: number;
  DocTotalFC: number;
  PaidToDate: number;
  PaidFC: number;
  GrosProfit: number;
  GrosProfFC: number;
  Ref1: string;
  Ref2: string | null;
  Comments: string;
  JrnlMemo: string;
  TransId: number | null;
  ReceiptNum: number | null;
  GroupNum: number;
  DocTime: number;
  SlpCode: number;
  TrnspCode: number;
  PartSupply: string;
  Confirmed: string;
  GrossBase: number;
  ImportEnt: number | null;
  CreateTran: string;
  SummryType: string;
  UpdInvnt: string;
  UpdCardBal: string;
  Instance: number;
  Flags: number;
  InvntDirec: string;
  CntctCode: string | null;
  ShowSCN: string;
  FatherCard: string | null;
  SysRate: number;
  CurSource: string;
  VatSumSy: number;
  DiscSumSy: number;
  DocTotalSy: number;
  PaidSys: number;
  FatherType: string;
  GrosProfSy: number;
  UpdateDate: string;
  IsICT: string;
  CreateDate: string;
  Volume: number;
  VolUnit: number;
  Weight: number;
  WeightUnit: number;
  Series: number;
  TaxDate: string;
  Filler: string | null;
  DataSource: string;
  StampNum: string | null;
  isCrin: string;
  FinncPriod: number;
  UserSign: number;
  selfInv: string;
  VatPaid: number;
  VatPaidFC: number;
  VatPaidSys: number;
  UserSign2: number;
  WddStatus: string;
  draftKey: number | null;
  TotalExpns: number;
  TotalExpFC: number;
  TotalExpSC: number;
  DunnLevel: number | null;
  Address2: string | null;
  LogInstanc: number;
  Exported: string;
  StationID: number;
  Indicator: string | null;
  NetProc: string;
  AqcsTax: number;
  AqcsTaxFC: number;
  AqcsTaxSC: number;
  CashDiscPr: number;
  CashDiscnt: number;
  CashDiscFC: number;
  CashDiscSC: number;
  ShipToCode: string | null;
  LicTradNum: string | null;
  PaymentRef: string | null;
  WTSum: number;
  WTSumFC: number;
  WTSumSC: number;
  RoundDif: number;
  RoundDifFC: number;
  RoundDifSy: number;
  CheckDigit: string | null;
  Form1099: string | null;
  Box1099: string | null;
  submitted: string;
  PoPrss: string;
  Rounding: string;
  RevisionPo: string;
  Segment: number;
  ReqDate: string | null;
  CancelDate: string | null;
  PickStatus: string;
  Pick: string;
  BlockDunn: string;
  PeyMethod: string | null;
  PayBlock: string;
  PayBlckRef: string | null;
  MaxDscn: string;
  Reserve: string;
  Max1099: number;
  CntrlBnk: string | null;
  PickRmrk: string | null;
  ISRCodLine: string | null;
  ExpAppl: number;
  ExpApplFC: number;
  ExpApplSC: number;
  Project: string | null;
  DeferrTax: string;
  LetterNum: string | null;
  FromDate: string | null;
  ToDate: string | null;
  WTApplied: number;
  WTAppliedF: number;
  BoeReserev: string;
  AgentCode: string | null;
  WTAppliedS: number;
  EquVatSum: number;
  EquVatSumF: number;
  EquVatSumS: number;
  Installmnt: number;
  VATFirst: string;
  NnSbAmnt: number;
  NnSbAmntSC: number;
  NbSbAmntFC: number;
  ExepAmnt: number;
  ExepAmntSC: number;
  ExepAmntFC: number;
  VatDate: string | null;
  CorrExt: string | null;
  CorrInv: number | null;
  NCorrInv: number | null;
  CEECFlag: string;
  BaseAmnt: number;
  BaseAmntSC: number;
  BaseAmntFC: number;
  CtlAccount: string | null;
  BPLId: number | null;
  BPLName: string | null;
  VATRegNum: string | null;
  TxInvRptNo: string | null;
  TxInvRptDt: string | null;
  KVVATCode: string | null;
  WTDetails: string | null;
  SumAbsId: number;
  SumRptDate: string | null;
  PIndicator: string;
  ManualNum: string | null;
  UseShpdGd: string;
  BaseVtAt: number;
  BaseVtAtSC: number;
  BaseVtAtFC: number;
  NnSbVAt: number;
  NnSbVAtSC: number;
  NbSbVAtFC: number;
  ExptVAt: number;
  ExptVAtSC: number;
  ExptVAtFC: number;
  LYPmtAt: number;
  LYPmtAtSC: number;
  LYPmtAtFC: number;
  ExpAnSum: number;
  ExpAnSys: number;
  ExpAnFrgn: number;
  DocSubType: string;
  DpmStatus: string;
  DpmAmnt: number;
  DpmAmntSC: number;
  DpmAmntFC: number;
  DpmDrawn: string;
  DpmPrcnt: number;
  PaidSum: number;
  PaidSumFc: number;
  PaidSumSc: number;
  FolioPref: string | null;
  FolioNum: string | null;
  DpmAppl: number;
  DpmApplFc: number;
  DpmApplSc: number;
  LPgFolioN: string | null;
  Header: string | null;
  Footer: string | null;
  Posted: string;
  OwnerCode: string | null;
  BPChCode: string | null;
  BPChCntc: string | null;
  PayToCode: string | null;
  IsPaytoBnk: string | null;
  BnkCntry: string | null;
  BankCode: string | null;
  BnkAccount: string | null;
  BnkBranch: string | null;
  isIns: string;
  TrackNo: string | null;
  VersionNum: string;
  LangCode: string | null;
  BPNameOW: string;
  BillToOW: string;
  ShipToOW: string;
  RetInvoice: string;
  ClsDate: string | null;
  MInvNum: string | null;
  MInvDate: string | null;
  SeqCode: number | null;
  Serial: number | null;
  SeriesStr: string | null;
  SubStr: string | null;
  Model: string;
  TaxOnExp: number;
  TaxOnExpFc: number;
  TaxOnExpSc: number;
  TaxOnExAp: number;
  TaxOnExApF: number;
  TaxOnExApS: number;
  LastPmnTyp: string | null;
  LndCstNum: string | null;
  UseCorrVat: string;
  BlkCredMmo: string;
  OpenForLaC: string;
  Excised: string;
  ExcRefDate: string | null;
  ExcRmvTime: string | null;
  SrvGpPrcnt: number;
  DepositNum: number | null;
  CertNum: number | null;
  DutyStatus: string;
  AutoCrtFlw: string;
  FlwRefDate: string | null;
  FlwRefNum: number | null;
  VatJENum: number;
  DpmVat: number;
  DpmVatFc: number;
  DpmVatSc: number;
  DpmAppVat: number;
  DpmAppVatF: number;
  DpmAppVatS: number;
  InsurOp347: string;
  IgnRelDoc: string;
  BuildDesc: string;
  ResidenNum: string;
  Checker: string | null;
  Payee: string | null;
  CopyNumber: number;
  SSIExmpt: string | null;
  PQTGrpSer: string | null;
  PQTGrpNum: string | null;
  PQTGrpHW: string;
  ReopOriDoc: string | null;
  ReopManCls: string | null;
  DocManClsd: string;
  ClosingOpt: number;
  SpecDate: string | null;
  Ordered: string;
  NTSApprov: string;
  NTSWebSite: string | null;
  NTSeTaxNo: string | null;
  NTSApprNo: string | null;
  PayDuMonth: string | null;
  ExtraMonth: string | null;
  ExtraDays: string | null;
  CdcOffset: number;
  SignMsg: string | null;
  SignDigest: string | null;
  CertifNum: string | null;
  KeyVersion: string | null;
  EDocGenTyp: string;
  ESeries: string | null;
  EDocNum: string | null;
  EDocExpFrm: string | null;
  OnlineQuo: string;
  POSEqNum: string | null;
  POSManufSN: string | null;
  POSCashN: string | null;
  EDocStatus: string;
  EDocCntnt: string | null;
  EDocProces: string;
  EDocErrCod: string | null;
  EDocErrMsg: string | null;
  EDocCancel: string;
  EDocTest: string;
  EDocPrefix: string | null;
  CUP: string | null;
  CIG: string | null;
  DpmAsDscnt: string;
  Attachment: string | null;
  AtcEntry: number | null;
  SupplCode: string | null;
  GTSRlvnt: string;
  BaseDisc: number;
  BaseDiscSc: number;
  BaseDiscFc: number;
  BaseDiscPr: number;
  CreateTS: number;
  UpdateTS: number;
  SrvTaxRule: string;
  AnnInvDecR: string | null;
  Supplier: string | null;
  Releaser: string | null;
  Receiver: string | null;
  ToWhsCode: string | null;
  AssetDate: string | null;
  Requester: string | null;
  ReqName: string | null;
  Branch: string | null;
  Department: string | null;
  Email: string | null;
  Notify: string | null;
  ReqType: number;
  OriginType: string;
  IsReuseNum: string;
  IsReuseNFN: string;
  DocDlvry: string;
  PaidDpm: number;
  PaidDpmF: number;
  PaidDpmS: number;
  EnvTypeNFe: number;
  AgrNo: string | null;
  IsAlt: string;
  AltBaseTyp: number;
  AltBaseEnt: number | null;
  AuthCode: string | null;
  StDlvDate: string | null;
  StDlvTime: string | null;
  EndDlvDate: string | null;
  EndDlvTime: string | null;
  VclPlate: string | null;
  ElCoStatus: string | null;
  AtDocType: string | null;
  ElCoMsg: string | null;
  PrintSEPA: string;
  FreeChrg: number;
  FreeChrgFC: number;
  FreeChrgSC: number;
  NfeValue: number;
  FiscDocNum: number | null;
  RelatedTyp: number;
  RelatedEnt: number | null;
  CCDEntry: number | null;
  NfePrntFo: number;
  ZrdAbs: number | null;
  POSRcptNo: string | null;
  FoCTax: number;
  FoCTaxFC: number;
  FoCTaxSC: number;
  TpCusPres: string | null;
  ExcDocDate: string | null;
  FoCFrght: number;
  FoCFrghtFC: number;
  FoCFrghtSC: number;
  InterimTyp: number;
  PTICode: string | null;
  Letter: string | null;
  FolNumFrom: string | null;
  FolNumTo: string | null;
  FolSeries: string | null;
  SplitTax: number;
  SplitTaxFC: number;
  SplitTaxSC: number;
  ToBinCode: string | null;
  PriceMode: string | null;
  PoDropPrss: string;
  PermitNo: string | null;
  MYFtype: string | null;
  DocTaxID: string | null;
  DateReport: string | null;
  RepSection: string | null;
  ExclTaxRep: string;
  PosCashReg: string | null;
  DmpTransID: string | null;
  ECommerBP: string | null;
  EComerGSTN: string | null;
  Revision: string;
  RevRefNo: string | null;
  RevRefDate: string | null;
  RevCreRefN: string | null;
  RevCreRefD: string | null;
  TaxInvNo: string | null;
  FrmBpDate: string | null;
  GSTTranTyp: string | null;
  BaseType: number;
  BaseEntry: number | null;
  ComTrade: string;
  UseBilAddr: string | null;
  IssReason: number;
  ComTradeRt: string;
  SplitPmnt: string;
  SOIWizId: string | null;
  SelfPosted: string;
  EnBnkAcct: string | null;
  EncryptIV: string | null;
  DPPStatus: string;
  SAPPassprt: string | null;
  EWBGenType: string | null;
  CtActTax: number;
  CtActTaxFC: number;
  CtActTaxSC: number;
  EDocType: string;
  QRCodeSrc: string | null;
  AggregDoc: string;
  DataVers: number;
  ShipState: string | null;
  ShipPlace: string | null;
  CustOffice: string | null;
  FCI: string | null;
  NnSbCuAmnt: number;
  NnSbCuSC: number;
  NnSbCuFC: number;
  ExepCuAmnt: number;
  ExepCuSC: number;
  ExepCuFC: number;
  AddLegIn: string | null;
  LegTextF: string | null;
  IndFinal: string;
  DANFELgTxt: string | null;
  PostPmntWT: string;
  QRCodeSPGn: string | null;
  FCEPmnMean: string;
  U_Container_Status: string | null;
  U_Shipping_Line: string | null;
  U_Vessel_Name: string | null;
  U_T_Operator: string | null;
  U_Container_Type: string | null;
  U_BLNo: string;
  U_VoyageNo: string | null;
  U_Discharge_Date: string | null;
  U_DeliveryType: string | null;
  U_CustomReleaseDT: string | null;
  U_CustomReleaseNo: string | null;
  U_ShippingLineDT: string | null;
  U_ShippingLineDONo: string | null;
  U_Truck: string;
  U_DriverID: string | null;
  U_DriverName: string | null;
  U_Consignee: string | null;
  U_TransportCo: string | null;
  U_ForwarderCHA: string | null;
  U_Name: string | null;
  U_TIN: string | null;
  U_VRN: string | null;
  U_TotalDays: string | null;
  U_FreeDays: string | null;
  U_BillableDays: string | null;
  U_SingleDays: string | null;
  U_DoubleDays: string | null;
  U_NoOfContainer: string | null;
  U_NoOfContainer40: string | null;
  U_FreeD: string | null;
  U_SingleD: string | null;
  U_DD: string | null;
  U_QOUTVALIDITY: string | null;
  U_STDocEntry: string;
  U_Flag: string;
  U_STLine: string;
  U_AbsID: string | null;
  U_ARITEMJE: string | null;
  U_ReleaseNo: string;
  U_ReleaseDate: string | null;
  U_DelOrdNo: string;
  U_DelOrdDate: string | null;
  U_ExitDate: string | null;
  U_ExitTime: string | null;
  U_DepDate: string | null;
  U_DepTime: string | null;
  U_TrailorNo: string;
  U_ShippingLine: string | null;
  U_VesselName: string | null;
  U_Voyage: string | null;
  U_TerminalOperator: string | null;
  U_BaseDoc: string | null;
  U_BaseDocNo: number;
  U_ForwarderName: string | null;
  U_Rectime1: string | null;
  U_Transporter: string;
  U_DepTime1: string | null;
  U_Remarks: string;
  U_Driver: string;
  U_DriverLicense: string;
  U_Officer: string | null;
  U_ConsigneeName: string | null;
  U_20Feet: string | null;
  U_40Feet: string | null;
  U_StrippedGoods: string | null;
  U_SACode: string | null;
  U_ContDetails: string | null;
  U_Type: string;
  U_Terminal: string | null;
  U_DischargeDate: string | null;
  U_SuppCharge: string | null;
  U_Cancellation: string | null;
  U_StorageDays: string | null;
  U_LONo: string | null;
  U_LODate: string | null;
  U_MRN: string | null;
  U_ContType: string;
  U_TransCode: string;
  U_RecType: string;
  U_NomMode: string | null;
  U_InvDocEntry: number;
  U_AuthUser: string;
  U_OutType: string;
  U_AgrrID: string | null;
  U_ChargesType: string;
  U_ADays: number;
  U_ContainerDeliverd: string;
  U_Open20: string | null;
  U_Stripping20: string | null;
  U_Open40: string | null;
  U_Stripping40: string | null;
  U_RevTraCust: string;
  U_Identification: string | null;
  U_TrCtrNo: string | null;
  U_RecTime: string | null;
  U_ExitTime1: number;
  U_CAFCont: string | null;
  U_GateOutDate: string;
  U_Local_Transit: string | null;
  U_LocalDG_TransitDG: string | null;
  U_SisterCo_OtherCo: string | null;
  U_InvoiceDate: string | null;
  U_DAYSSTAY: string | null;
  U_rctvnum: string | null;
  U_rctvcode: string | null;
  U_znumber: string | null;
  U_vfdinvoicenum: string | null;
  U_idate: string | null;
  U_itime: string | null;
  U_Message: string | null;
  U_Duplicate: string;
  U_BLNo1: string;
  U_ValidUntill: string;
  U_FreeDaysValid: string;
  U_FreeDaysValidDate: string | null;
  U_DriverLicence: string | null;
  U_GrossWeight: number;
  U_GoodsDetails: string | null;
  U_STDocNum: string | null;
  U_20FeetC: number;
  U_40FeetC: number;
  U_StrippedGoodsC: number;
  U_BKNO: string | null;
  U_DOCNO: string | null;
  U_TransRef: string | null;
  U_TruckN: string | null;
  U_TraillerN: string;
};
