

export type LoadingPermitHeader = {
  DocEntry: number;
  DocNum: number;
  Period: number;
  Instance: number;
  Series: number;
  Handwrtten: string;
  Canceled: string;
  Object: string;
  LogInst: number | null;
  UserSign: number;
  Transfered: string;
  Status: string;
  CreateDate: string;
  CreateTime: number;
  UpdateDate: string;
  UpdateTime: number;
  DataSource: string;
  RequestStatus: string;
  Creator: string;
  Remark: string | null;
  U_ADDON: string;
  U_Type: string;
  U_OutType: string;
  U_HMDDN: string;
  U_INVNUM: string;
  U_INVDE: string;
  U_DLDN: string | null;
  U_DLDE: string | null;
  U_RLNO: string | null;
  U_TCCODE: string;
  U_TCNAME: string;
  U_TRUCKNO: string;
  U_REMARK: string;
  U_DocDate: string;
  U_ETime: number;
  U_ValidUntil: string;
  U_FDV: string;
  U_DOD: string | null;
  U_RD: string | null;
  U_Driver: string;
  U_DLIcNo: string;
  U_TRLNO: string;
  U_AUTHBY: string;
  U_DDDE: string;
  U_DDDN: string;
  U_AID: string;
  U_AName: string;
};
