/**
 * Received payment (incoming payment) header row as returned from the API / database (ORCT).
 * Field names match the source columns, including legacy spellings/casing.
 * Nullability and primitive types are inferred from the provided sample row.
 */
export type ReceivedPaymentHeader = {
  DocEntry: number;
  DocNum: number;
  DocType: string;
  Canceled: string;
  Handwrtten: string;
  Printed: string;
  DocDate: string;
  DocDueDate: string;
  CardCode: string;
  CardName: string;
  Address: string | null;
  DdctPrcnt: number;
  DdctSum: number;
  DdctSumFC: number;
  CashAcct: string | null;
  CashSum: number;
  CashSumFC: number;
  CreditSum: number;
  CredSumFC: number;
  CheckAcct: string | null;
  CheckSum: number;
  CheckSumFC: number;
  TrsfrAcct: string;
  TrsfrSum: number;
  TrsfrSumFC: number;
  TrsfrDate: string;
  TrsfrRef: string | null;
  PayNoDoc: string;
  NoDocSum: number;
  NoDocSumFC: number;
  DocCurr: string;
  DiffCurr: string;
  DocRate: number;
  SysRate: number;
  DocTotal: number;
  DocTotalFC: number;
  Ref1: string;
  Ref2: string | null;
  CounterRef: string | null;
  Comments: string | null;
  JrnlMemo: string;
  TransId: number;
  DocTime: number;
  ShowAtCard: string;
  SpiltTrans: string;
  CreateTran: string;
  Flags: number;
  CntctCode: string | null;
  DdctSumSy: number;
  CashSumSy: number;
  CredSumSy: number;
  CheckSumSy: number;
  TrsfrSumSy: number;
  NoDocSumSy: number;
  DocTotalSy: number;
  ObjType: string;
  StornoRate: number;
  UpdateDate: string;
  CreateDate: string;
  ApplyVAT: string;
  TaxDate: string;
  Series: number;
  confirmed: string;
  ShowJDT: string;
  BankCode: string | null;
  BankAcct: string | null;
  DataSource: string;
  UserSign: number;
  LogInstanc: number;
  VatGroup: string | null;
  VatSum: number;
  VatSumFC: number;
  VatSumSy: number;
  FinncPriod: number;
  VatPrcnt: number;
  Dcount: number;
  DcntSum: number;
  DcntSumFC: number;
  DcntSumSy: number;
  SpltCredLn: string;
  PrjCode: string | null;
  PaymentRef: string | null;
  Submitted: string;
  Status: string;
  PayMth: string | null;
  BankCountr: string | null;
  FreightSum: number;
  FreigtFC: number;
  FreigtSC: number;
  BoeAcc: string | null;
  BoeNum: string | null;
  BoeSum: number;
  BoeSumFc: number;
  BoeSumSc: number;
  BoeAgent: string | null;
  BoeStatus: string | null;
  WtCode: string | null;
  WtSum: number;
  WtSumFrgn: number;
  WtSumSys: number;
  WtAccount: string | null;
  WtBaseAmnt: number;
  Proforma: string;
  BoeAbs: string | null;
  BpAct: string;
  BcgSum: number;
  BcgSumFC: number;
  BcgSumSy: number;
  PIndicator: string;
  PaPriority: string;
  PayToCode: string | null;
  IsPaytoBnk: string;
  PBnkCnt: string | null;
  PBnkCode: string | null;
  PBnkAccnt: string | null;
  PBnkBranch: string | null;
  WizDunBlck: string;
  WtBaseSum: number;
  WtBaseSumF: number;
  WtBaseSumS: number;
  UndOvDiff: number;
  UndOvDiffS: number;
  BankActKey: string | null;
  VersionNum: string;
  VatDate: string | null;
  TransCode: string | null;
  PaymType: string;
  TfrRealAmt: number;
  CancelDate: string | null;
  OpenBal: number;
  OpenBalFc: number;
  OpenBalSc: number;
  BcgTaxSum: number;
  BcgTaxSumF: number;
  BcgTaxSumS: number;
  TpwID: number;
  ChallanNo: string | null;
  ChallanBak: string | null;
  ChallanDat: string | null;
  WddStatus: string;
  BcgVatGrp: string | null;
  BcgVatPcnt: number;
  SeqCode: number | null;
  Serial: number | null;
  SeriesStr: string | null;
  SubStr: string | null;
  BSRCode: string | null;
  LocCode: string | null;
  WTOnhldPst: number;
  UserSign2: number;
  BuildDesc: string;
  ResidenNum: string;
  OperatCode: string | null;
  UndOvDiffF: number;
  MIEntry: number;
  FreeText1: string | null;
  FreeText2: string | null;
  FreeText3: string | null;
  ShowDocNo: string;
  TDSInterst: number;
  TDSCharges: number;
  CUP: string | null;
  CIG: string | null;
  MIType: string | null;
  SupplCode: string | null;
  BPLId: number | null;
  BPLName: string | null;
  VATRegNum: string | null;
  BPLCentPmt: string;
  DraftKey: number | null;
  TDSFee: number;
  MinHeadCL: string | null;
  SEPADate: string | null;
  OwnerCode: string | null;
  AgrNo: string | null;
  CreateTS: number;
  UpdateTS: number;
  TDSType: string | null;
  DrNo: string | null;
  PmntWTCert: string;
  EnPBnkAcct: string | null;
  EncryptIV: string | null;
  DPPStatus: string;
  PriceMode: string | null;
  AtcEntry: number | null;
  Attachment: string | null;
  EnblDpmTax: string;
  SignMsg: string | null;
  SignDigest: string | null;
  CertifNum: string | null;
  KeyVersion: string | null;
  QRCodeSPGn: string | null;
  DataVers: number;
  U_Consignee: string | null;
  U_TrackingId: string | null;
};
